[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "simple-smartsheet"
version = "0.1.3"
description = "Python library to interact with Smartsheet objects"
authors = ["Dmitry Figol <git@dmfigol.me>"]
license = "MIT"

readme = "README.md"

homepage = "https://github.com/dmfigol/simple-smartsheet"
repository = "https://github.com/dmfigol/simple-smartsheet"

keywords = ["smartsheet"]

classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Intended Audience :: Developers",
]


[tool.poetry.dependencies]
python = ">=3.6"
marshmallow = "^3.0.0b19"
requests = "^2.20"
attrs = "^18.2"
cattrs = "^0.9.0"
pendulum = "^2.0"
python-decouple = "^3.1"
mypy-extensions = "^0.4.1"

[tool.poetry.dev-dependencies]
ipython = "^7.0"
flake8 = "^3.5"
mypy = "^0.641.0"
ipdb = "^0.11.0"
black = "^18.3-alpha.0"
isort = "^4.3"
